Add SharingUtils with two example for sharing article
miLibris/android-milibris-pdf-reader-sdk pull request #5
Opened 2021-03-03 14:55 UTC by Hadidi-007

Update the README.md to detail the sharing article examples

Jira: https://lekiosk.atlassian.net/browse/PUB-289

2021-03-03 15:26 UTC, MaximeLM requested changes

2021-03-03 15:26 UTC, MaximeLM commented on README.md
> +If your miLibris content has articles, you can implement your own sharing solution by implementing void shareArticleContent. Two examples are provided in the sample project:
Suggestion: replace "void shareArticleContent" with "shareArticleContent"

2021-03-03 15:26 UTC, MaximeLM commented on app/src/main/java/com/milibris/pdfreader/sampleapp/sharing/SharingUtils.kt
> +        intent.putExtra(Intent.EXTRA_EMAIL, arrayOf("test@test.com"))
You should leave the recipient blank, it's the user that will fill it.

2021-03-03 15:26 UTC, MaximeLM commented on app/src/main/java/com/milibris/pdfreader/sampleapp/sharing/SharingUtils.kt
> +                    "$title  $editionTitle, $editionSubtitle"
You should put editionTitle and editionSubtitle between () as in the comment on line 68

2021-03-03 15:26 UTC, MaximeLM commented on app/src/main/java/com/milibris/pdfreader/sampleapp/sharing/SharingUtils.kt
> +                } ?: "$title  $editionTitle"
same here, the edition title should be between parenthesis

2021-03-04 09:57 UTC, MaximeLM approved these changes

2021-03-19 09:56 UTC, Ajmir-milibris commented on app/src/main/java/com/milibris/pdfreader/sampleapp/sharing/SharingUtils.kt
> +            .append("/${article.mid}").toString()
```suggestion
            "$kioskURL/share/article/$issueMid/${article.mid]"
```

2021-03-19 09:59 UTC, Ajmir-milibris commented on app/src/main/java/com/milibris/pdfreader/sampleapp/sharing/SharingUtils.kt
> +            article.editionTitle.let { editionTitle ->
editionTitle doesn't seem to be optional ? 
If that's the case then it's not necessary to use the 'let' on it.

2021-03-19 10:05 UTC, Ajmir-milibris approved these changes

2021-03-19 10:09 UTC, Hadidi-007 commented on app/src/main/java/com/milibris/pdfreader/sampleapp/sharing/SharingUtils.kt
> +            .append("/${article.mid}").toString()
you need to replace the ] with } so i can commit your suggestion

2021-03-19 11:11 UTC, Ajmir-milibris approved these changes

2021-03-19 13:06 UTC, merged